args <- commandArgs(trailingOnly=FALSE)
p <- sub('^--file=', '', args[grep('^--file=',args)][1])
source(file.path(dirname(p),'../03_analysis/code/data_rules.R'))
stopifnot(identical(known_bpq_med(1,NA,2),FALSE))
stopifnot(identical(known_bpq_med(2,1,2),TRUE))
stopifnot(identical(known_bpq_med(1,2,1),FALSE))
stopifnot(is.na(known_bpq_med(1,NA,9)))
stopifnot(is.na(known_bpq_med(1,7,2)))
stopifnot(identical(known_bpq_med(2,NA,NA),FALSE))
stopifnot(identical(TRUE | NA,TRUE),is.na(FALSE | NA))
cat('PASS: direct-use priority, negative skips, refusal/unknown and three-valued component logic\n')
