"""Build a standalone supplement from corrected aggregate outputs."""
from pathlib import Path
import importlib.util
import pandas as pd
from docx import Document
ROOT=Path(__file__).resolve().parents[2];R=ROOT/'04_outputs/results';F=ROOT/'04_outputs/figures';OUT=ROOT/'05_manuscript/supplementary'
OUT.mkdir(exist_ok=True)
spec=importlib.util.spec_from_file_location('builder',Path(__file__).with_name('06_build_manuscript_docx.py'));b=importlib.util.module_from_spec(spec);spec.loader.exec_module(b)
doc=Document();b.configure_document(doc);doc.add_heading('Supplementary File',0)
b.add_body_paragraph(doc,'Leg-to-trunk fat distribution and metabolic dysfunction beyond total adiposity in US adults. This supplement documents variable construction, selection, association sensitivity analyses and the exploratory temporal prediction benchmark. It accompanies the revised manuscript; no clinical application is validated.')
text=[]
def para(x):
    paragraph=b.add_body_paragraph(doc,x)
    paragraph.paragraph_format.line_spacing=1.08
    for run in paragraph.runs: b.set_run_font(run,size=10)
    text.append(x)
def table(frame,label,title,note,widths=None):
    frame=frame.fillna('');frame.to_csv(OUT/(label.replace(' ','_')+'.csv'),index=False)
    b.add_dataframe_table(doc,frame,dict(label=label,title=title,note='Note. '+note,widths=widths or [9360//len(frame.columns)]*len(frame.columns),font_size=8),page_break=True)
    text.extend([label+' '+title,frame.to_string(index=False),note])
def fmtp(x):return '< .001' if x<.001 else f'{x:.3f}'
def num(x):return f'{x:.3f}'
doc.add_heading('Contents and document map',1)
para('This is the single Supplementary File accompanying the manuscript. The manuscript contains Tables 1–3 and Figures 1–3. All items labelled S are contained here: Methods S1 (variables and analysis rules), Methods S2 (prediction modelling), Tables S1–S2 (component associations and incremental prediction), S3–S5 including S4b (selection, missingness and medication), S6a–S6b (sensitivity estimates and denominators), S7a–S7c (nonlinearity and diagnostics), S8 (development/test description), S9 and S9b (tuning and cycle counts), S10 (selected parameters), S11 (calibration), Figures S1 (nonlinear associations), S2 (calibration), and S3 (participant flow). Reporting Checklist A maps every STROBE cross-sectional item; Checklist B maps TRIPOD+AI items. Labels and section names provide stable cross-references independent of pagination.')
doc.add_heading('Supplementary Methods S1',1)
para('NHANES public modules were joined by SEQN within cycles G, H, I and J (2011–2018). Identical BPQ variable names and documented negative recommendation skips apply in all four cycles. Source modules are DEMO, DXX, DXXAG, BMX, BPX, HDL, TRIGLY, GLU, BPQ, DIQ and SMQ. Other downloaded biomarker modules are not part of this manuscript’s models. Eligible participants completed the examination, were aged 20–59 years, had positive examination weights and no recorded pregnancy. Unknown pregnancy was not classified as pregnancy. The fasting design includes every record with positive WTSAF2YR/4 and valid masked stratum and PSU before domain restriction.')
para('DXA exposure: (DXXLLFAT + DXXRLFAT)/DXXTRFAT, masses in grams, natural-log transformed. DXAEXSTS = 1 and positive regional and total fat and height were required. Total, leg and trunk fat-mass indices divide kilograms by squared height in metres. Android/gynoid ratio (DXXAGRAT) and visceral fat (DXXVFATM/1000, kg) require DXXAGST = 1 and positive values. Whole-body DXA follows the public standardized NHANES examination and central quality-control protocol; public validity flags do not remove body-size-related nonmeasurement. See CDC DXX and DXXAG cycle documentation cited in the manuscript.')
q=pd.read_csv(R/'data_quality_checks.csv').set_index('metric').value
ref=pd.read_csv(R/'nonlinear_prediction_curve.csv').iloc[0]
para(f'The log exposure uses the primary-sample survey-weighted mean {q.raw_log_exposure_weighted_mean:.8f} and SD {q.raw_log_exposure_weighted_sd:.8f}, pooled across sexes. Alternative exposures use R scale(): unweighted mean and sample SD within the relevant analysis domain. The reference profile for Figures 1 and S1 is age {ref.RIDAGEYR:g} years, poverty-income ratio {ref.INDFMPIR:g}, total fat-mass index {ref.total_fmi:.4f} kg/m², ethnicity code {ref.race_ethnicity}, cycle {ref.cycle}, education code {ref.education} and smoking {ref.smoking}. Continuous values are unweighted medians and categorical values are modes. These conditional curves are not population-standardized marginal prevalences.')
para('Medication coding: BPQ020 (diagnosed hypertension), BPQ040A (ever advised blood-pressure medication), BPQ050A (currently taking it); BPQ080 (high cholesterol diagnosis), BPQ090D (ever advised cholesterol medication), BPQ100D (currently taking it). Current use 1 means yes and 2 means no. If current use is unavailable, recommendation 2 means no treatment; if recommendation is missing and history is 2, treatment is also coded no. Recommendation 7/9 (refused/unknown) is not interpreted as no. Insulin (DIQ050) and oral diabetes medication (DIQ070): current use 1/2 has yes/no meaning, otherwise DIQ010 2/3 (no/borderline) implies no treatment under the retained algorithm. DIQ010 = 1 identifies diagnosed diabetes; 2/3 are negative, other responses unknown. Measurement or treatment positivity takes precedence over another missing component input. Negativity requires all relevant inputs to be negative. Four classifiable components are required for the primary two-of-four endpoint.')
para('Measured inputs: LBXTR ≥150 mg/dL; LBDHDD <40 mg/dL for men or <50 for women; BPXSY1–4 and BPXDI1–4 averaged separately over strictly positive available readings, with systolic ≥130 or diastolic ≥85 mmHg; LBXGLU ≥100 mg/dL. The positive generic lipid-treatment indicator makes both lipid components positive. The single-count sensitivity uses max(number of measured lipid abnormalities, lipid-treatment indicator), plus blood-pressure and glucose components; it requires both measured lipids and a known treatment indicator. The measured-only sensitivity requires all four measured components and both blood-pressure means. The five-component secondary outcome is any three of the four primary components and central obesity (BMXWAIST ≥102 cm for men, ≥88 cm for women); all five must be classifiable. Uniform waist thresholds are an operational choice, not ethnic-specific clinical thresholds.')
para('Covariates: RIDAGEYR in years; RIAGENDR 1 male/2 female; RIDRETH3 1 Mexican American, 2 other Hispanic, 3 non-Hispanic White, 4 non-Hispanic Black, 6 non-Hispanic Asian, 7 other/multiracial; DMDEDUC2 1 below ninth grade, 2 ninth–eleventh grade, 3 high school/GED, 4 some college/associate degree, 5 college or above; INDFMPIR poverty-income ratio; smoking never if SMQ020=2, current if SMQ040=1/2, former if SMQ020=1 and SMQ040=3, otherwise missing. Education and ethnicity enter as categorical variables. Age uses a natural spline with 3 degrees of freedom. The full adjustment set is sex, age spline, ethnicity, cycle, education, income, smoking and total fat-mass index, with exposure-by-sex interaction. Joint leg/trunk models omit total fat-mass index; BMI sensitivity replaces it. Minimal adjustment retains age spline, ethnicity, cycle and total fat-mass index. Unadjusted estimates include exposure, sex and their interaction only.')
para('The dated local revision amendment specifies the corrections before the rerun; it is not independent prospective registration. Earlier results and code remain in a baseline archive. Raw public files were not changed. No additional clinical endpoint adjudication was performed. Predictors and endpoint were contemporaneous public measurements; no additional analyst blinding was implemented. The analysis is a research benchmark, not a deployable diagnostic rule.')
para('CDC questionnaire sources: https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/BPQ_G.htm ; corresponding 2013/BPQ_H, 2015/BPQ_I and 2017/BPQ_J pages document the same medication recommendation branches. Survey rescaled-bootstrap reference implementation: https://raw.githubusercontent.com/cran/survey/master/R/bootstrap.R .')
tables=b.prepare_publication_tables()
for key in ['table_s1','table_s2']:
    meta=b.TABLE_META[key];table(tables[key],meta['label'],meta['title'],meta['note'].removeprefix('Note. '),meta['widths'])
flow=pd.read_csv(R/'participant_flow.csv').pivot(index='stage',columns='cycle',values='n').reindex(['MEC adults 20-59, not pregnant','Positive fasting weight','Valid required DXA','All outcome components','Primary complete']);flow['Total']=flow.sum(axis=1);flow=flow.reset_index()
table(flow,'Table S3','Sequential participant flow','Counts are unweighted and sequential. Differences between adjacent rows quantify exclusions. DXA, dual-energy X-ray absorptiometry; MEC, mobile examination center.',[2960,1280,1280,1280,1280,1280])
table(pd.read_csv(R/'missingness_before_selection.csv'),'Table S4','Missing inputs before outcome and covariate selection','Denominator is 4,415 eligible participants with positive fasting weights and valid required DXA. Missing counts overlap; they must not be summed. Variable definitions appear in Methods S1. DXA, dual-energy X-ray absorptiometry.',[4400,2480,2480])
clinical=pd.read_csv(ROOT/'02_data/derived/harmonized_analysis_data.csv',low_memory=False)
clinical=clinical[clinical.primary_domain.astype(str).str.lower().eq('true')]
rows=[]
for sex,g in clinical.groupby('sex'):
    for v in ['antihypertensive_med','lipid_med_proxy','insulin_med','oral_diabetes_med','diagnosed_diabetes','high_tg','low_hdl','high_bp','high_glucose']:
        known=g[v].notna(); positive=g.loc[known,v].astype(str).str.lower().eq('true');w=g.loc[known,'pooled_fasting_weight']
        rows.append({'Sex':sex,'Characteristic':v,'Known n':int(known.sum()),'Positive n':int(positive.sum()),'Weighted %':f'{100*(positive*w).sum()/w.sum():.1f}'})
table(pd.DataFrame(rows),'Table S4b','Medication and metabolic-component profile','Primary population; missing medication status can coexist with a classifiable positive component. Percentages use the available-case survey-weight denominator for each row.',[1200,3960,1400,1400,1400])
table(pd.read_csv(R/'skip_rule_verification.csv'),'Table S5','Verification of known negative medication skips','Among the same 4,415 participants. Negative skip means diagnosis=yes, recommendation=no, downstream current-use question missing. Remaining unknown should be zero for this branch.',[1760,1600,3000,3000])
ss=pd.read_csv(R/'sensitivity_sex_contrasts.csv');ns=pd.read_csv(R/'sensitivity_sample_sizes.csv').set_index('analysis');rows=[]
for (analysis,exposure),g in ss.groupby(['analysis','exposure'],sort=False):
    g=g.set_index('contrast');v=ns.loc[analysis]
    rows.append({'Analysis / exposure':analysis.replace('_',' ')+' / '+exposure,'n / cases':f'{v.n} / {v.cases}','Male PR (95% CI)':f'{g.loc["Men","prevalence_ratio"]:.2f} ({g.loc["Men","ci_low"]:.2f}–{g.loc["Men","ci_high"]:.2f})','Female PR (95% CI)':f'{g.loc["Women","prevalence_ratio"]:.2f} ({g.loc["Women","ci_low"]:.2f}–{g.loc["Women","ci_high"]:.2f})','Ratio (95% CI)':f'{g.loc["Interaction","prevalence_ratio"]:.2f} ({g.loc["Interaction","ci_low"]:.2f}–{g.loc["Interaction","ci_high"]:.2f})','Interaction p':fmtp(g.loc['Interaction','p_value'])})
table(pd.DataFrame(rows),'Table S6a','Complete sensitivity estimates','PR, prevalence ratio; CI, confidence interval; BMI, body mass index. Ratio = female/male PR. Exposure scaling and exact adjustment sets are defined in Methods S1. All sensitivity analyses are restricted to the corrected primary domain plus their own necessary complete inputs; they are not independent replications.',[2660,1100,1550,1550,1550,950])
table(ns.reset_index().rename(columns={'analysis':'Analysis','n':'Total n','cases':'Cases','men':'Male n','women':'Female n','male_cases':'Male cases','female_cases':'Female cases'}),'Table S6b','Sex-specific analysis denominators and events','All counts are unweighted. Cases are defined by each analysis outcome; male_cases and female_cases refer to that outcome.',[2760,1100,1100,1100,1100,1100,1100])
nt=pd.read_csv(R/'nonlinear_interaction_test.csv');nt['statistic']=nt.statistic.map(num);nt['p_value']=nt.p_value.map(fmtp)
table(nt,'Table S7a','Cubic-model design-based Wald tests','All tests are from the same cubic exposure model. A nonsignificant additional-curvature test does not prove identical curves. Overall exposure-by-sex heterogeneity uses all three interaction terms.',[4200,1300,1300,1300,1260])
di=pd.read_csv(R/'survey_diagnostics.csv');di['value']=di.value.map(lambda x:f'{x:.4f}' if x%1 else str(int(x)))
table(di,'Table S7b','Survey-model diagnostics','Fitted values above one are possible in modified Poisson models; robust PR estimates do not make these valid individual probabilities. Both models converged. No clipping was used in calculations. PR, prevalence ratio.',[6200,3160])
sup=pd.read_csv(R/'exposure_support.csv');lo=sup.p05.max();hi=sup.p95.min()
for col in ['p05','p50','p95']:sup[col]=sup[col].map(num)
table(sup,'Table S7c','Weighted empirical exposure support by sex',f'Quantiles of pooled standardized log ratio. Shared 5th–95th percentile range: {lo:.3f} to {hi:.3f}. This describes overlap, not a clinical interval.')
b.add_figure(doc,dict(path=F/'figure_s1_nonlinearity.png',label='Figure S1',caption='Cubic exposure model at the reference profile in Methods S1, with pointwise 95% design-based t intervals (upper panel) and weighted exposure distribution (lower panel). Grey shading marks the shared sex-specific 5th–95th percentile range. Curves are displayed from −2 to 2 pooled SD units; distribution tails outside this window are omitted. CI, confidence interval; SD, standard deviation.',width=6.1,alt='Cubic fitted means with sex-specific exposure distributions.'))
table(pd.read_csv(R/'development_test_description.csv'),'Table S8','Development and temporal-test characteristics','Continuous values are survey-weighted mean (SD), with missing counts. Categorical values are unweighted n (weighted %). Code definitions and units are in Methods S1. Noncases: development 1,906; test 422. SD, standard deviation.',[2050,3450,3860])
doc.add_heading('Supplementary Methods S2',1)
para('Panel A: RIDAGEYR, sex, race_ethnicity, cycle, education, INDFMPIR, smoking. Panel B adds BMXBMI; C adds BMXWAIST; D adds total_fmi, log_leg_trunk_ratio, ag_ratio and vat_kg. The D-versus-C comparison evaluates these total and regional adiposity measures jointly. Numeric predictors use median imputation and StandardScaler fitted only in each training fold. Categoricals use mode imputation and OneHotEncoder(handle_unknown="ignore"). Unknown cycle levels map to all-zero cycle indicators. Feature assessment used the recorded public measurements without additional analyst blinding. Spline models add SplineTransformer with five knots, degree three, include_bias=False, constant extrapolation, default uniform knot placement. Imputation and scaling use unweighted training-feature distributions; fitting and evaluation use survey weights.')
para('Development uses leave-one-cycle-out GroupKFold (three folds), selecting minimum mean weighted validation log loss, with deterministic parameter-string tie-breaking after rounding mean loss to six decimals. Logistic models: L2 penalty, liblinear, C in {0.1,1,10}, max_iter=2000 (linear) or 3000 (spline). XGBoost candidates: (depth, learning rate, trees) = (2,0.03,250), (3,0.03,250), (3,0.05,180); min_child_weight=5, subsample=0.8, colsample_bytree=0.8, reg_lambda=2, binary:logistic objective, logloss evaluation, n_jobs=1. All unspecified settings use library defaults from the recorded versions. Seed 20260726. The fitted preprocessing and estimator objects are saved locally for every panel and model; the code is available in GitHub release v1.0.0 (see manuscript); fitted models are regenerated locally.')
para('No over-/undersampling, synthetic class balancing, decision-threshold optimization, holdout recalibration, model updating or fairness analysis was performed. Survey fitting weights are normalized to mean one. Outputs are probabilities rather than clinical decisions; threshold metrics and an implementation pathway are not claimed. Same-examination outcomes do not support future-risk forecasting. There was no formal model-development sample-size calculation; fixed eligible public data determined the sample. Model-class comparisons are exploratory and their small observed differences do not establish superiority or equivalence.')
para('Bootstrap: for every stratum draw n_h−1 PSUs with replacement, multiplying each original participant weight by selected PSU multiplicity times n_h/(n_h−1). The test sample has 15 strata and two represented PSUs in each. One thousand identical replicate weight sets are applied to all twelve fixed prediction vectors. Percentile intervals are conditional on model development and are not corrected for multiple model comparisons. Calibration is weighted logistic outcome regression on predicted logit with a free intercept and slope; probabilities are clipped to [10^−6,1−10^−6] only for this calculation. Calibration curves use ten unweighted probability-quantile bins with weighted mean prediction and outcome proportion; these bins are descriptive, without bin-wise confidence intervals.')
tune=pd.read_csv(R/'ml_development_tuning.csv');tune.cv_log_loss=tune.cv_log_loss.map(num);tune.fold_log_losses=tune.fold_log_losses.map(lambda x:', '.join(f'{v:.4f}' for v in __import__('json').loads(x)))
table(tune,'Table S9','All development tuning candidates','Fold losses follow GroupKFold order (2013–2014, 2011–2012, 2015–2016). Model selection uses development only. CV, cross-validation.',[1200,1500,2800,1200,2660])
p=pd.read_csv(ROOT/'02_data/derived/harmonized_analysis_data.csv',low_memory=False);p=p[p.primary_domain.astype(str).str.lower().eq('true')];p['event']=p.metabolic_dysfunction.astype(str).str.lower().eq('true')
folds=p.groupby('cycle').agg(n=('SEQN','size'),cases=('event','sum')).reset_index()
table(folds,'Table S9b','Cycle and validation-fold counts','Each of the first three rows serves once as the development validation fold; the other two rows are its training data. The 2017–2018 row is temporal testing only.')
met=pd.read_csv(R/'ml_temporal_metrics.csv');table(met[['panel','model','selected_parameters']],'Table S10','Selected hyperparameters for every final model','Each selected pipeline is refitted on all 3,220 development observations. The 751 test observations never enter fitting. Full settings and library versions are stated in Methods S2 and the manuscript.',[1500,2300,5560])
cal=pd.read_csv(R/'ml_calibration_intervals.csv');cal.columns=['panel','model','quantile','intercept','slope'];rows=[]
for _,row in met.iterrows():
    ci=cal[(cal.panel==row.panel)&(cal.model==row.model)].set_index('quantile')
    rows.append(dict(Panel=row.panel,Model=row.model,Intercept=f'{row.calibration_intercept:.3f} ({ci.loc[.025,"intercept"]:.3f}–{ci.loc[.975,"intercept"]:.3f})',Slope=f'{row.calibration_slope:.3f} ({ci.loc[.025,"slope"]:.3f}–{ci.loc[.975,"slope"]:.3f})'))
table(pd.DataFrame(rows),'Table S11','Joint calibration estimates and 95% rescaled-bootstrap intervals','Ideal joint intercept is 0 and slope 1. The intercept is not calibration-in-the-large with a fixed unit slope. All 1,000 replicates yielded calibration estimates for every model.',[1300,2460,2800,2800])
b.add_figure(doc,dict(path=F/'figure_s2_calibration.png',label='Figure S2',caption='Descriptive calibration of full DXA-panel models in the 2017–2018 temporal sample. Points are weighted means within ten probability-quantile bins; lines join bins and are not smoothed estimates. Dashed line denotes perfect calibration. Overall calibration uncertainty is in Table S11. DXA, dual-energy X-ray absorptiometry.',width=6.0,alt='Observed versus predicted proportions for the three full-panel models.'))
b.add_figure(doc,dict(path=F/'figure_s3_participant_flow.png',label='Figure S3',caption='Participant flow across NHANES 2011–2018. Counts are unweighted and sequential; exclusion counts equal differences between adjacent eligibility stages. The diagram starts with examined adults meeting the age and recorded-pregnancy criteria, not all originally sampled survey participants. Table S3 gives cycle-specific counts. DXA, dual-energy X-ray absorptiometry; NHANES, National Health and Nutrition Examination Survey.',width=6.1,alt='Five sequential selection stages from 14,100 eligible examined adults to 3,971 complete cases, with exclusion counts and temporal partition.'))
doc.add_heading('Transparency',1)
para('The source survey obtained written consent under NCHS ethics oversight, as cited in the manuscript. The Ethics Committee of IST Hochschule für Management und Sport, Düsseldorf, Germany, confirmed that a separate ethics opinion was not required for this secondary analysis of deidentified public data. No specific funding was received for this work. The authors declare no conflicts of interest. Author contributions and acknowledgments are reported in the manuscript. There was no patient involvement in this secondary analysis. Code is available in GitHub release v1.0.0 (see manuscript). Local analysis freezing is not independent preregistration.')
for filename,title in [('strobe-cross-sectional-checklist.md','Reporting Checklist A: STROBE cross-sectional'),('tripod-ai-checklist.md','Reporting Checklist B: TRIPOD+AI')]:
    h=doc.add_heading(title,1);h.paragraph_format.page_break_before=True
    lines=(ROOT/'05_manuscript/quality_control'/filename).read_text().splitlines()
    for line in lines:
        if line and not line.startswith(('#','|')):para(line)
    rows=[[c.strip() for c in line.strip('|').split('|')] for line in lines if line.startswith('|') and not line.startswith('|---')]
    frame=pd.DataFrame(rows[1:],columns=rows[0])
    b.add_dataframe_table(doc,frame,dict(label='',title='',note='Locations refer to named sections and labelled tables or figures in the Manuscript (M) or this Supplementary File (S).',widths=[650,1250,2800,4660],font_size=8),page_break=False)
    if filename=='tripod-ai-checklist.md':
        from docx.oxml import OxmlElement
        for row in doc.tables[-1].rows:
            if row.cells[0].text in ('12b','26','27a'):
                row._tr.get_or_add_trPr().append(OxmlElement('w:cantSplit'))
    text.extend([title,frame.to_string(index=False)])
from document_presentation import apply_presentation
apply_presentation(doc)
doc.save(OUT/'nhanes_leg_to_trunk_supplement.docx');(OUT/'supplement.txt').write_text('\n\n'.join(text));print('Standalone supplement built.')
